"""create leads activities and webhook events

Revision ID: bc56044ea24c
Revises:
Create Date: 2026-09-25 18:53:04.280116

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc56044ea24c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Autogenerated from app/models, then reviewed by hand: column types and nullability, server
# defaults, CHECK/UNIQUE/FK constraint names (from the naming convention), FK ON DELETE rules,
# and DESC ordering on the list/timeline indexes.
def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "leads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=32), server_default="META_ADS", nullable=False),
        sa.Column("campaign_id", sa.String(length=255), nullable=True),
        sa.Column("form_id", sa.String(length=255), nullable=True),
        sa.Column("ad_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="NEW", nullable=False),
        sa.Column("meta_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('NEW', 'CONTACTED', 'QUALIFIED', 'CONVERTED', 'LOST')",
            name=op.f("ck_leads_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
        sa.UniqueConstraint("external_id", name=op.f("uq_leads_external_id")),
    )
    op.create_index(
        "ix_leads_created_at", "leads", [sa.literal_column("created_at DESC")], unique=False
    )
    op.create_index(
        "ix_leads_status_created_at",
        "leads",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('LEAD_CREATED', 'LEAD_UPDATED', 'STATUS_CHANGED')",
            name=op.f("ck_activities_type"),
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_activities_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_index(
        "ix_activities_lead_id_created_at",
        "activities",
        ["lead_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_event_id", sa.String(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "outcome IN ('CREATED', 'UPDATED', 'UNCHANGED')", name=op.f("ck_webhook_events_outcome")
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_webhook_events_lead_id_leads"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint(
            "source", "external_event_id", name=op.f("uq_webhook_events_source_external_event_id")
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("webhook_events")
    op.drop_index("ix_activities_lead_id_created_at", table_name="activities")
    op.drop_table("activities")
    op.drop_index("ix_leads_status_created_at", table_name="leads")
    op.drop_index("ix_leads_created_at", table_name="leads")
    op.drop_table("leads")
